#mercure:
#    hubs:
#        default:
#            url: '%env(MERCURE_URL)%'
#            public_url: '%env(MERCURE_PUBLIC_URL)%'
#            jwt:
#                secret: '%env(MERCURE_JWT_SECRET)%'
#                publish: '*'
mercure:
    hubs:
        default:
            url: https://localhost/.well-known/mercure
            jwt:
                secret: '!ChangeMe!'
                publish: ['foo', 'https://example.com/users/dunglas']
#                subscribe: ['bar', 'https://example.com/bar']
#                algorithm: 'hmac.sha256'
#                value: 'eyJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdLCJwYXlsb2FkIjp7InVzZXIiOiJodHRwczovL2V4YW1wbGUuY29tL3VzZXJzL2R1bmdsYXMiLCJyZW1vdGVBZGRyIjoiMTI3LjAuMC4xIn19fQ.ehpwH0DpIUo-ep5cGcj75MyprAOpgZgubl-frYFqYO0 '