vich_uploader:
    db_driver: orm
    mappings:
        profiles_images:
            uri_prefix: '%app.path.profiles_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.profiles_images%'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            delete_on_remove: true
            delete_on_update: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
